### ISSUE TITLE
replace_fillval_by_nan could not handle int type data

### ISSUE THREAD

**Issue by Beforerr** [SciQLop/speasy#204]
Data like `the_efw_l1.the_efw` is of integer type., so `res[res == fill_value] = np.nan` raises error.

Since the data is not in speasy cdaweb, I attach a yaml file

```
the_efw_l1:
  inventory_path: spdf/THEMIS/THE/L1/EFW
  master_cdf: https://spdf.gsfc.nasa.gov/pub/data/themis/the/l1/efw/2021/the_l1_efw_20210102_v01.cdf
  split_frequency: daily
  split_rule: regular
  url_pattern: https://spdf.gsfc.nasa.gov/pub/data/themis/the/l1/efw/{Y}/the_l1_efw_{Y}{M:02d}{D:02d}_v\d+.cdf
  use_file_list: true
```
